version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgre
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d